apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: bachthyaglx/todo-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: TODO_BACKEND_URL
              value: http://todo-backend-svc:3000
