apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc
  namespace: project
spec:
  selector:
    app: todo-app
  type: LoadBalancer # LoadBalancer type service (Google Cloud)
  ports:
    - port: 80 # Expose port 80 for HTTP traffic
      targetPort: 3000
