apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/image-data"
  persistentVolumeReclaimPolicy: Retain
