apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashgenerator-dep # Name of the deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      containers:
        - name: hashgenerator
          image: hashgenerator:v1 # Image to be used for the container
