apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pingpong
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/bachthyaglx/pingpong-serverless
