# .github/workflows/build-and-push.yml

name: Build and deploy Log Output

on:
  push:
    paths:
      - "**.js"
      - "**/Dockerfile"
      - "**/kustomization.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        run: |
          docker build -t your-dockerhub-username/log-output:${{ github.sha }} .
          docker push your-dockerhub-username/log-output:${{ github.sha }}

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Set image tag
        run: kustomize edit set image PROJECT/IMAGE=your-dockerhub-username/log-output:${{ github.sha }}

      - name: Commit new image tag
        uses: EndBug/add-and-commit@v9
        with:
          add: "kustomization.yaml"
          message: "Update image to ${{ github.sha }}"
