apiVersion: v1
kind: Service
metadata:
  name: log-output-pingpong-service
spec:
  type: ClusterIP
  selector:
    app: log-output
  ports:
    - name: pingpong
      port: 3032
      protocol: TCP
      targetPort: 3034
    - name: get-log-output
      port: 3011
      protocol: TCP
      targetPort: 3033
