name: Deploy to GKE

on:
  push:
    branches:
      - "**"

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-west1-b
  DEPLOYMENT_NAME: dwk-environments
  SERVICE: dwk-environments
  REPOSITORY: gcp-repo

jobs:
  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          export_default_credentials: true

      - name: Set up kubectl
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Set namespace based on branch
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "NAMESPACE=project" >> $GITHUB_ENV
          else
            echo "NAMESPACE=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Create namespace if not exists
        run: |
          kubectl get namespace $NAMESPACE || kubectl create namespace $NAMESPACE

      - name: Deploy to GKE
        run: |
          kustomize build . | kubectl apply -n $NAMESPACE -f -
          kubectl rollout status deployment $DEPLOYMENT_NAME -n $NAMESPACE
