apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
  namespace: project
spec:
  storageClassName: my-example-pv
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /tmp/kube
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3d-mycluster-agent-0 # ✅ Replace with your actual node name (`kubectl get nodes`)
