apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup-cronjob
  namespace: project
spec:
  schedule: "0 3 * * *" # Every day at 03:00 UTC
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: pg-backup
              image: postgres:16
              env:
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: todo-db-secret
                      key: POSTGRES_PASSWORD
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /var/secrets/google/key.json
              command:
                - /bin/sh
                - -c
                - |
                  export DATE=$(date +\%Y-\%m-\%dT\%H-%M-%S)
                  pg_dump -h todo-postgres -U postgres todos > /backup/todos-$DATE.sql
                  gsutil cp /backup/todos-$DATE.sql gs://YOUR_BUCKET_NAME/
              volumeMounts:
                - name: backup-volume
                  mountPath: /backup
                - name: gcp-sa-key
                  mountPath: /var/secrets/google
                  readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: backup-volume
              emptyDir: {}
            - name: gcp-sa-key
              secret:
                secretName: gcs-sa-secret
