apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Default is "project", GitHub Actions will oeverride this based on branch
namespace: project

resources:
  - manifests/deployment.yaml
  - manifests/service.yaml

images:
  - name: PROJECT/IMAGE
    newName: europe-west1-docker.pkg.dev/pingpong-463502/gcp-repo/dwk-environments
