apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
  namespace: exercises
spec:
  type: LoadBalancer # LoadBalancer type service (Google Cloud)
  selector:
    app: pingpong
  ports:
    - port: 80 # Expose port 80 for HTTP traffic
      protocol: TCP
      targetPort: 3000
