apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: bachthyaglx/todo-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "75m"
              memory: "96Mi"
            limits:
              cpu: "200m"
              memory: "192Mi"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: DATABASE_URL
