apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {}
      containers:
        - name: log-writer
          image: yourdockerhub/log-writer:v1
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/data
        - name: log-reader
          image: yourdockerhub/log-reader:v1
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/data
